### ISSUE TITLE
Incorrectly mapped password conditions

### ISSUE THREAD

**Issue by kmehrunes** [AuthGuard/AuthGuard#57]
When given passwords config with conditions for capital letters, small letters, special characters, or digits, the config is always mapped to false regardless of the provided value. 
Example:
```yaml
  passwords:
    algorithm: scrypt
    conditions:
      includeCaps: true
      minLength: 6
```
This won't lead to enforcing capital letters and only the length will be checked.
