### ISSUE TITLE
Expose SCrypt and BCrypt configuration

### ISSUE THREAD

**Issue by kmehrunes** [AuthGuard/AuthGuard#59]
We should be able to fine-tune SCrypt and BCrypt in the configuration while maintaining the defaults
```yaml
passwords:
    algorithm: bcrypt
    bcrypt:
       saltSize: 16
```
